### ISSUE TITLE
Devices folder missing under Prelayout directory

### ISSUE THREAD

**Issue by ombhilare999** [vsdip/avsdcmp_3v3_sky130#1]
When I open .sch file in xschem I'm getting following error 
I guess devices folder is missing, please check once.

![image](https://user-images.githubusercontent.com/40693854/117135302-6125e200-adc4-11eb-8d01-e9b25c33c908.png)

**Comment by MalayMDas** [comment]
Hi Omkar,
If you did a standard installation of Xschem, please try opening xschem from folder ~/.xschem/xschem_library/xschem_sky130/ . This folder would have the xschemrc file, that would initialize and set the file paths appropriately.

Thanks
